import Foundation

// Orchestrator-owned. Builders fill in the suite functions in their own
// files; do not edit this file.

suite("Shared")
await sharedTests()

suite("Core")
await coreTests()

suite("Tools")
await toolsTests()
await newToolsTests()

suite("Infra")
await infraTests()

suite("E2E")
await e2eTests()

finishTests()
